Sorting
PinkaCourt/stockIndexes pull request #3
Opened 2021-11-07 17:52 UTC by PinkaCourt

В общем некорректно работает только сортировка для полей где разные валюты. С одной стороны оттуда сортировку можно и убрать, а с другой она мне там наверно еще понадобится. Поэтому ничего делать я с этим не  буду. И вообще надо разнести одну табличку на несколько по валюте, но это потом.

![image](https://user-images.githubusercontent.com/50292671/140656029-1267e28e-193f-46fb-acf5-f9225ff8dcb7.png)

2021-11-07 18:49 UTC, denydavy requested changes

2021-11-07 18:49 UTC, denydavy commented on src/common/utils.ts
> +  return direction === "asc" ? result : result.reverse();
есть ощущение, что можно это делать в сортировке, тогда ты можешь убрать необходимость делать .reverse и выиграешь по скорости/памяти.

2021-11-07 18:49 UTC, denydavy commented on src/components/Tinkoff/index.tsx
> +    return compareFn(
мне кажется, что если сделать это в редаксе ( мемоизированно-параметризированный селектор ), то будет лучше, как с точки зрения архитектуры, так и производительности. Но это не точно, но я бы сделал так )

2021-11-07 18:49 UTC, denydavy commented on src/components/Moex/index.tsx
> +    ) as StocksMRBCFull[];
Я заметил, что ты довольно часто прибегаешь к приведению типов через каст ( as тип ). Это по большому счету хак, т.к. ты говоришь тайпскрипту что то что он тут увидит это тип А, в то время как у тебя эта функция возвращает А | В. Тебе нужно либо сделать общую структуру, если это имеет смысл ( тип А и Б, по сути могут иметь одинаковый набор полей, которые по разному обзываются в разных API ), либо иметь все таки разные функции сортировки. Или.... почитать ниже, про то, что можно работать с данными в другом месте :)

2021-11-08 17:38 UTC, PinkaCourt commented on src/common/utils.ts
> +  return direction === "asc" ? result : result.reverse();
переделала

2021-11-08 17:38 UTC, PinkaCourt commented on src/components/Tinkoff/index.tsx
> +    return compareFn(
тоже перетащила

2021-11-08 17:39 UTC, PinkaCourt commented on src/components/Moex/index.tsx
> +    ) as StocksMRBCFull[];
тоже убрала

2021-11-08 17:58 UTC, PinkaCourt commented
одну сортировку починила, другую сломала. ОЯЕБУ

2021-11-09 19:38 UTC, denydavy commented on src/common/constants.ts
> +export const currencyMap = {
💯

2021-11-09 21:53 UTC, denydavy commented
Что то все равно получается сложно, я про направления эти твои. Я тут накидал пример, посмотри, может тебе по похожей схеме можно упростить? https://codesandbox.io/s/affectionate-chaum-z704h

2021-11-11 21:49 UTC, PinkaCourt commented on src/common/constants.ts
> +export const currencyMap = {
выкинула к хренам

2021-11-27 08:39 UTC, denydavy commented
вроде ок, наливай в мастер)

2021-11-27 11:28 UTC, merged